### ISSUE TITLE
It may better to remove #if DEBUG

### ISSUE THREAD

**Issue by miku1958** [isavynskyi/LayoutInspector#16]
Basically large APP will use multiple scheme and use different macro to distinguish, most of them may not in debug mode, and also we don't Introduce debug tool in release from pods, so it's no need to add #if DEBUG in func startLayoutInspection()

**Comment by isavynskyi** [comment]
@miku1958 yes, mentioned scenario makes sense, however:
- large app will use multiple schemes but opposite is also true - there are small apps which don't have such separation;
- same applies for pods structuring to exclude debug tool from release.Again, not all apps have it :(
Current approach keeps LayoutInspector's API consumers in safe and requires minimal effort to onboard it into the project

**Comment by miku1958** [comment]
@isavinskyi that's true... how about tell other others it's necessary to add Debug macro in readme?

**Comment by isavynskyi** [comment]
@miku1958 `DEBUG` macro already mentioned in Readme [here](https://github.com/isavynskyi/LayoutInspector#features)
